spring.application.name=byteassist-backend

# Add these properties to enable custom 404 handling
spring.web.resources.add-mappings=false

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=byteassist.bot@gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true