name: Build and Run Backend

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

jobs:
    build-and-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "21"

            - name: Cache Maven dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: Build backend
              run: |
                  cd backend
                  ./mvnw clean package -DskipTests
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  DATABASE_NAMESPACE: ${{ secrets.DATABASE_NAMESPACE }}
                  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
                  DATABASE_USER: ${{ secrets.DATABASE_USER }}
                  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}

            - name: Run backend
              run: |
                  cd backend
                  java -jar target/*.jar
