name: Run Tests

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

jobs:
    test-linux:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Java
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "24"

            - name: Cache Maven dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: Make mvnw executable
              run: chmod +x byteassist-backend/mvnw

            - name: Run Tests
              run: |
                  cd byteassist-backend
                  ./mvnw test

    test-windows:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Java
              uses: actions/setup-java@v3
              with:
                  distribution: "zulu"
                  java-version: "24"

            - name: Cache Maven dependencies
              uses: actions/cache@v3
              with:
                  path: C:\Users\runneradmin\.m2
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: Run Tests
              run: |
                  cd byteassist-backend
                  .\mvnw.cmd test
